### ISSUE TITLE
User Documentation - Requirement 2: Quick Start Guide

### ISSUE THREAD

**Issue by HectorBastidasRentadrone** [RentadroneCL/model-definition#10]
Rubric Open Source (Justin Flory)

*EVALUATION*: Yellow
*SUBJECT*: User Documentation - Requirement 2: Quick Start Guide
*DETAIL*: TQuick Start Guide does not completely cover the starting process, but gives a sufficient start.
*POSSIBLE SOLUTION*: Post the jupyter installation steps, (or whatever it takes) to be able to replicate the experiments

**Comment by dlsaavedra** [comment]
See new Readme

**Comment by HectorBastidasRentadrone** [comment]
Very nice @dlsaavedra! This is the link to see the solution https://github.com/RentadroneCL/model-definition/blob/master/README.md#quickstart
