### ISSUE TITLE
Incluir mas tipos de fallas en este orden:

### ISSUE THREAD

**Issue by HectorBastidasRentadrone** [RentadroneCL/model-definition#3]
- 1 celda afectada (son los paneles con un punto caliente en zonas  que no sea en las esquinas debido a soiling)
-  Varias celdas afectadas  (son los paneles con 2 o mas punto caliente en zonas  que no sean en las esquinas debido a soiling) @dlsaavedra
Nota: Colocar los nombres de las fallas en inglés como el resto

**Comment by dlsaavedra** [comment]
Prototipo de Falla de Celda listo.

**Comment by dlsaavedra** [comment]
Prototipo de Falla de Celda listo.
